'use client'

// This file is auto-generated by generate-entries.js
// Do not edit manually - regenerate with: nxcode generate

import { ReactNode } from 'react'

interface ProvidersProps {
  children: ReactNode
}

export function Providers({ children }: ProvidersProps) {
  return <>{children}</>
}
