# This file is auto-generated by generate-entries.js
# Do not edit manually - regenerate with: nxcode generate

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from routes.api import router as api_router

app = FastAPI(title="Nxcode App")

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Health check
@app.get("/health")
async def health_check():
    return {"status": "ok"}

# Routers
app.include_router(api_router, prefix="/api", tags=["api"])
